### ISSUE TITLE
use format strings in org-mode-blog-preamble/postamble

### ISSUE THREAD

**Issue by ghost** [howardabrams/dot-files#1]
I'm sorry for an issue in your dotfiles, but... :cat: 

I want to use a custom preamble/postamble the same way and tried to use some format strings like `%d` or `{{{date}}}` but none of them get replaced. Any chance to use them? I dont really like to mess around with big chunks of html within elisp config.

**Comment by howardabrams** [comment]
Sorry for the delay (and no problem about filing a bug against my dot files ... can't believe any one even looks at them).

I don't think those macros have any formatting in them. Since they are macros, you _could_ "pop out" of the macro and evaluate some Lisp expression. While I haven't tried it, perhaps something like:

```
:html-head-extra "<meta name=\"date\" content=\" ,(get-file-date) \">"
```

However, it sounds like this might be long and overly complicated to support. Of course, going that route, you could just set the `org-html-head`, `org-html-preamble`, and `org-html-postamble` variables.

Would be nice to have _template_ that you could read, parse and substitute, and then use as the `org-html-*` variables. For me, I just wanted to bare minimum, and then assumed I would use JavaScript to compensate for anything missing.

**Comment by ghost** [comment]
Hey there :smirk_cat: 

thanks for your help! Seems not to be what I was looking for, I thought I could use something like:

```
<p>Author: %a</p>
<p>Date %d<p>
...
```

Would be nice to have such `_preamble.html` file in the project folder and telling `:html-preamble` to include it. Thanks Mr. Abrams. :joy_cat:

**Comment by howardabrams** [comment]
Is the org-mode exporting postamble that already has most of that information good enough if you could style it with CSS (and maybe move it using JavaScript)?

**Comment by ghost** [comment]
:crying_cat_face:
